#!/bin/sh

set -o errexit

# Copy the Tingbot screen overlay into place
cp /opt/tingbot-os/tingbot-overlay.dtb /boot/overlays/tingbot-overlay.dtb

# Load the Tingbot screen overlay at boot
# The /boot/config.txt file was set aside in preinst
cp /boot/config.txt.tbbak /boot/config.txt
echo "" >> /boot/config.txt
echo "# Enable the Tingbot screen" >> /boot/config.txt
echo "dtparam=spi=on" >> /boot/config.txt
echo "dtoverlay=tingbot:xohms=80" >> /boot/config.txt

# Map the console tty to the screen for the boot
# The /boot/cmdline.txt file was set aside in preinst
sed "1 s/$/ fbcon=map:10 consoleblank=0/" /boot/cmdline.txt.tbbak > /boot/cmdline.txt

pip install pip==8.0.3
pip install wheel==0.29.0 setuptools==20.2.2
pip install pillow==2.9.0 requests==2.7.0 evdev==0.5.0

pip install git+https://github.com/tingbot/tbprocessd.git@v0.3
pip install git+https://github.com/tingbot/tingbot-python.git@v0.4.0

update-rc.d tbwifisetup defaults
update-rc.d tbwifisetup enable
systemctl enable tbprocessd
