#!/bin/sh

set -o errexit

if [ "$1" = "remove" -o "$1" = "abort-install" -o "$1" = "disappear" ]; then
    rm -f /boot/overlays/tingbot-overlay.dtb
fi

update-rc.d -f tbwifisetup remove

systemctl disable tbprocessd
systemctl disable tbbuttonsd
