#! /bin/sh
### BEGIN INIT INFO
# Provides:          tbwifisetup
# Required-Start:    checkroot
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Updates wpa_supplicant.conf
# Description:       Updates wpa_supplicant.conf
### END INIT INFO

# note: install and then run
# sudo update-rc.d tbwifisetup start 01 S

do_start () {
    cat /boot/networks.json | /usr/bin/tbwifisetup > /etc/wpa_supplicant/wpa_supplicant.conf
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload|status)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  *)
    echo "Usage: tbwifisetup [start]" >&2
    exit 3
    ;;
esac
